source/docs/3/basic_vector_styling.rst
source/docs/3/making_a_map.rst
source/docs/3/raster_styling_and_analysis.rst
source/docs/3/working_with_attributes.rst
source/docs/creating_basemaps_with_qtiles.rst
source/docs/downloading_osm_data.rst
source/docs/making_a_map.rst
source/docs/open_bil_bip_bsq_files.rst
source/docs/performing_spatial_queries.rst
source/docs/processing_python_scripts.rst
source/docs/working_with_projections.rst

Changed world to World
Corrected typos and inconsistencies

Minor edits

---

source/docs/3/animating_time_series.rst

line 80  :   atuomatically              = automatically
line 85  :  then Click                     = "click" lowercase
line 122:  Click save                     = Click Save. (Capital S and period at the end)
line 127:  year(total 18 images)  = added space between "year" and "("

Small typo's corrected

---

source/docs/3/performing_table_joins.rst

Line 130 :  by diving by            = should be probably "by dividing by"

Small typo corrected

---

source/docs/3/origin_destination_matrix.rst

Line 107  : We had 9 origin points  =  We had 13 origin points  (13 origins not 9 in the file !)
Line 142  : click on the origin point (OBJECTID_1 = 853046) in the canvas  == This point might not be in the resultset as the  points are randomly generated !
Line 142  : Topology tolerance as 0.0000150  -- (image says 0.000015)   => number of decimals seems off!   -and-  
Line 157  :  In Topology tollerance enter 0.000015. --  removed one "l"  (image says 0.000150)    => number of decimals seems off!
Line 167  :   In the :guilabel:`History` dialog, Select the lastest command(command used for Shortest path).  == should probably be
In the :guilabel:`History` dialog, select the latest command (command used for Shortest path).  = lowercase s (select)   remove s (lastest)     space after "command" …

small typo's and some small adjustments

---

source/docs/3/working_with_projections.rst

Line 66  :  "United kingdom feature to select it"  => Kingdom should probably be spelled with a capital K
Line 97 :  12.Click  => added space between 12.  and Click

Small corrections

---

source/docs/3/working_with_terrain.rst

line    24 :       http://earthexplorer.usgs.gov/  == changed to https
line    24 :       http://eros.usgs.gov/#/Find_Data/Products_and_Data_Available/GMTED2010 == changed to https
line    32 :       :guilabel:`Show` .  == remove superfluous space between ` and . Removed additional space
line    37 :       Click on the :guilabel:`Data Sets`.  ==  add "button" after "the", or remove "the".  Removed "the"
line   42  :       Click the :guilabel:`Results`.  ==  add "button" after "the", or remove "the". Removed "the", added "on" for consistency
line   64  :       http://www.gdal.org/formats_list.html>   == changed to https
line   77  :       Open :menuselection:`Layer --> Add Raster Layer`. == Open :menuselection:`Layer --> Add Layer --> Add Raster Layer`. Added  [[  --> Add Layer ]]
line …

Some corrections and changes

---

source/docs/3/interpolating_point_data.rst

Changed HTTP to HTTPS.
Removed two double words "the"

Small adjustments

---

source/docs/3/using_plugins.rst

line 115 : "QRS Tools"  should be "ORS Tools"  Typo corrected

Typo corrected

---

source/docs/3/downloading_osm_data.rst

Line 79 :  Choose should be started with a smal "c"  and "Longon" should be "London"

Typo's corrected

---

source/docs/credits.rst

Line 199 ; "Downloadeded" should be "Downloaded"  and the start of the link with "hhttps://www." should be "https://www."

Small typo's

---

source/docs/3/advanced_georeferencing.rst

Line 20 : URL of the Public laboratory seems to have changed from HTTP to HTTPS and also the name changed to https://publiclab.org
Line 22 : URL of the Public laboratory seems to have changed from HTTP to HTTPS and also the name changed to https://publiclab.org. also removed one superfluous space
Line 40 : "But that is cumbersome and practical. "should probably be : "But that is cumbersome and not practical." Added "not" to the sentence
Line 65 : "default ad choose ``LZW`` should probably be "default and choose ``LZW``. Changed "ad" to and"

Some minor changes

---

source/docs/3/advanced_raster_analysis.rst

Line 176 : "and  Change the"  should probably be : "and change the"
Line 234 : ``reclass Sheet1``  ==> QGIS 3.22.1 only shows ``Sheet1``
Line 239 : ``reclass Sheet1``  ==> QGIS 3.22.1 only shows ``Sheet1``

Small typos/grammar

---

source/docs/3/calculating_raster_area.rst

Line 287 : "..landcover.xlxs``  must be "..landcover.xlsx``

Typo in file extension XL:SX

---

source/docs/3/landuse_buffer.rst

Corrected some typo's

---

source/docs/3/solidwaste_mapping.rst

qgis  --> capital letters QGIS

One more typo corrected

---

source/docs/3/solidwaste_mapping.rst

below .   --> remove space   below.
Services Directory , Go to  --> Services Directory , go to
qgis.   --> capital letters  QGIS
contains 4 sheets  --> file contains 3 sheets now
5. In the Procedure : items 5. and 11. show number in Transifex
11. In the
:guilabel:`Date-defined override`  = :guilabel:`Data-defined override` 
21.Next we will  |  Procedure : item 21. shows number in Transifex
Date-defined Size Legend   = Data-defined Size Legend
Remark:
I downloaded the spreadsheet from the site Open Data. It now contains 3 pages if I'm not mistaken. Can't find sheet Data Events anymore

Corrected some minor typos and some other bits & bobs

---

source/docs/3/block_world_styling.rst

../../source/docs/3/block_world_styling.rst:41
removed superfluous space
../../source/docs/3/block_world_styling.rst:121 
Scroll done the  == Scroll down the

Corrected two typo's

---

source/docs/3/contour_3d_styling.rst

Line 93: added word "button" that seemed to be missing.

Missing word "button"

---

source/docs/3/isometric_buildings.rst

line 55: geopackage  == GeoPackage
line 60 : toronto == Toronto
line 99 : appling  ==  applying
line 145 : top color  == top color.  (period at the end :-) )

Few typos corrected

---

source/docs/3/interactive_reveal_maps.rst

line 64 : enter an expressions  ==>  expression (singular)
line 104 : the ``point`` layer ==>> the ''mask'' layer

Corrected two typos

---

source/docs/3/multi_criteria_overlay.rst

Please have a look at point 16.
Expression states: "raster_water_merged@1" > 0
Picture .. image:: /static/3/multi_criteria_overlay/images/16.png states:
"raster_water_merged@1" > 1

Fixed some typo and formatting
